export class Locations {
    locationList: string[] = [
        "Aamchit",
        "Ain Zhalta",
        "Ain el Remmaneh",
        "Akkar",
        "Aley",
        "Aley District",
        "Amioun",
        "Arz (Cedar)",
        "Baalbek",
        "Batroûn District",
        "Batroun",
        "Baabda",
        "Beirut",
        "Beiteddine",
        "Bekaa Kafra",
        "Bekaa Plain",
        "Bcharre",
        "Bebnin",
        "Bhamdoun",
        "Bhamdoun el Mhatta",
        "Bekaa Valley",
        "Bint Jbeil",
        "Bir Hassan",
        "Bir al-Abd",
        "Bsharri",
        "Byblos",
        "Chouf",
        "Damour",
        "Deir Mimas",
        "Deir el Qamar",
        "Dahr el Ahmar",
        "Danniyeh",
        "Douma",
        "Ehden",
        "Faqra",
        "Forn el Chebbak",
        "Hammana",
        "Hamra",
        "Haret Hreik",
        "Haret Sakher",
        "Hasbaya",
        "Hazmiyeh",
        "Hermel",
        "Jaita",
        "Jbeil",
        "Jdeideh",
        "Jerd El Akoura",
        "Jezzine",
        "Jezzîne District",
        "Jiyeh",
        "Jounieh",
        "Jal el Dib",
        "Kadisha Valley",
        "Keserwan",
        "Kfarnabrakh",
        "Kfardebian",
        "Kfarhbab",
        "Kfarhbeb",
        "Kourah",
        "Lehfed",
        "Maknouniye",
        "Mansourieh",
        "Mar Moussa",
        "Marjaayoun",
        "Mazraat El Touffah",
        "Mazraat Yachouh",
        "Mtein",
        "Mishmish",
        "Miniyeh-Danniyeh District",
        "Monte Verde",
        "Nabatieh",
        "Nahr Ibrahim",
        "Nahr al-Kalb",
        "Ouâdi Qadisha",
        "Qaraoun",
        "Qadisha Valley",
        "Qornet El Sawda",
        "Raouche",
        "Rashaya",
        "Rashaya District",
        "Roum",
        "Sahel Alma",
        "Saydet el Hosn",
        "Sidon",
        "Sawfar",
        "Sourat",
        "Tabarja",
        "Taanayel",
        "Tannourine",
        "Tayyouneh",
        "Tripoli",
        "Tyre",
        "Tyre District",
        "Wadi Abou Jamil",
        "Wadi Chahrour",
        "Wadi El Jamous",
        "Zahle",
        "Zaarour",
        "Zaarour Club",
        "Zgharta",
        "Zaarour",
        "Zaarour Club"
    ];

    constructor() { }
}
