export class ProfessionCategories {
    categories: string[] = [
      "Accountant",
      "Actor",
      "Actuary",
      "Advertising Manager",
      "Aerospace Engineer",
      "Air Traffic Controller",
      "Airline Pilot",
      "Animal Breeder",
      "Animal Trainer",
      "Aquarist",
      "Architect",
      "Aromatherapist",
      "Art Director",
      "Astrophysicist",
      "Auto Mechanic",
      "Automotive Technician",
      "Aviation Mechanic",
      "Baker",
      "Biochemist",
      "Biologist",
      "Bricklayer",
      "Broadcast Journalist",
      "Carpenter",
      "Caterer",
      "Chef",
      "Chiropractor",
      "Claims Adjuster",
      "Clinical Psychologist",
      "Community Health Worker",
      "Compliance Officer",
      "Computer Programmer",
      "Construction Worker",
      "Content Creator",
      "Copywriter",
      "Corporate Trainer",
      "Cosmetologist",
      "Court Reporter",
      "Criminal Investigator",
      "Criminal Lawyer",
      "Dental Hygienist",
      "Dentist",
      "Dermatologist",
      "Digital Marketer",
      "Dietitian",
      "Documentary Filmmaker",
      "Economist",
      "Ecologist",
      "Elevator Installer",
      "Electrician",
      "Embryologist",
      "EMT",
      "Environmental Scientist",
      "Event Planner",
      "Fashion Designer",
      "Fashion Stylist",
      "Film Director",
      "Financial Analyst",
      "Firefighter",
      "Fitness Trainer",
      "Flight Attendant",
      "Forensic Scientist",
      "Furniture Designer",
      "Game Designer",
      "Glassblower",
      "Graphic Designer",
      "Hair Stylist",
      "Hematologist",
      "Historian",
      "Home Inspector",
      "Home cleaner",
      "Horticulturist",
      "Industrial Designer",
      "Information Security Analyst",
      "Insurance Underwriter",
      "Interior Designer",
      "Interpreter",
      "Jeweler",
      "Journalist",
      "Land Surveyor",
      "Landscape Architect",
      "Linguist",
      "Makeup Artist",
      "Marine Biologist",
      "Maritime Engineer",
      "Marketing Manager",
      "Mechanical Engineer",
      "Medical Illustrator",
      "Medical Assistant",
      "Meteorologist",
      "Meteorologist",
      "Mining Engineer",
      "Model",
      "Musician",
      "Neurologist",
      "Nurse",
      "Nutritionist",
      "Occupational Therapist",
      "Optometrist",
      "Orthodontist",
      "Orthopedic Surgeon",
      "Painter",
      "Paralegal",
      "Park Ranger",
      "Pet Groomer",
      "Petroleum Engineer",
      "Pharmacist",
      "Phlebotomist",
      "Photographer",
      "Physician",
      "Physiotherapist",
      "Pilot",
      "Plastic Surgeon",
      "Plumber",
      "Podiatrist",
      "Police Officer",
      "Politician",
      "Probation Officer",
      "Process Engineer",
      "Professor",
      "Project Manager",
      "Public Health Educator",
      "Quality Control Inspector",
      "Radiographer",
      "Real Estate Agent",
      "Recruiter",
      "Referee",
      "Relocation Specialist",
      "Risk Analyst",
      "Satellite Engineer",
      "Salesman",
      "Scientist",
      "Secretary",
      "SEO Specialist",
      "Social Worker",
      "Social Media Manager",
      "Software Developer",
      "Statistician",
      "Surgeon",
      "Surgeon",
      "Tax Consultant",
      "Taxidermist",
      "Teacher",
      "Technical Writer",
      "Therapist",
      "Theater Director",
      "Traffic Engineer",
      "Travel Agent",
      "Translator",
      "Tutor",
      "Underwater Welder",
      "Urban Planner",
      "Video Editor",
      "Vegan Chef",
      "Veterinarian",
      "Virtual Reality Developer",
      "Waiter",
      "Water Quality Technician",
      "Web Developer",
      "Wine Sommelier",
      "Writer",
      "Yoga Instructor",
      "Zoologist",
      "Zumba Instructor"
    ];
  
    constructor() { }
  }
  